#!/usr/bin/env python3
"""Generate the offline vendor table from IEEE MA-L, MA-M and MA-S CSV downloads.
Usage: python3 tools/build_wifi_vendors.py oui.csv mam.csv oui36.csv
"""
import csv
import datetime
import json
import pathlib
import sys

entries = {}
for name in sys.argv[1:]:
    with open(name, encoding='utf-8-sig', newline='') as source:
        for row in csv.DictReader(source):
            prefix = row['Assignment'].strip().upper()
            if len(prefix) not in (6, 7, 9) or any(c not in '0123456789ABCDEF' for c in prefix):
                raise ValueError(f'Invalid prefix: {prefix}')
            entries[prefix] = row['Organization Name'].strip()
if len(entries) < 30000:
    raise ValueError('Expected full IEEE registries, refusing incomplete input')
output = pathlib.Path(__file__).resolve().parents[1] / 'third_party/ieee/wifi_vendors.inc'
output.write_text('// Generated by tools/build_wifi_vendors.py; see README.md for provenance.\n' +
                  ''.join('{' + json.dumps(k) + ', ' + json.dumps(v, ensure_ascii=False) + '},\n'
                          for k, v in sorted(entries.items())), encoding='utf-8')
print(f'{len(entries)} entries written to {output}')

output.with_name('wifi_vendor_snapshot.hpp').write_text(
    '#pragma once\n#define WIFI_VENDOR_SNAPSHOT_DATE "' + datetime.date.today().isoformat() + '"\n')
